import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import { AUTH_COMPLETE_URL } from "@/lib/auth-redirect";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex h-dvh flex-col overflow-hidden">
        <ClerkProvider
          signInUrl="/sign-in"
          signUpUrl="/sign-up"
          signInForceRedirectUrl={AUTH_COMPLETE_URL}
          signUpForceRedirectUrl={AUTH_COMPLETE_URL}
          signInFallbackRedirectUrl={AUTH_COMPLETE_URL}
          signUpFallbackRedirectUrl={AUTH_COMPLETE_URL}
        >
          {children}
        </ClerkProvider>
        <Analytics />
      </body>
    </html>
  );
}
